config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  authenticated :user do
    root 'pages#home', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :authentications, only: [:destroy]

  root 'pages#home' #set site to default to the new home page

  resources :categories, shallow: true do 
    
    resources :posts
    get 'posts/tags/:tag', to: 'posts#index', as: 'post_tag'
    
    resources :artworks do
      resources :pictures do
        #should this be inside picture? - probably
        resources :notes, only: [:new, :create, :destroy]
      end
      member do
        patch 'create_picture'

      end
    end

    get 'artworks/tags/:tag', to: 'artworks#index', as: 'artwork_tag'
  end #end of categories
  
  
  resources :posts do

    resources :comments, module: :posts do
    end
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
      put 'set_completed' #put is used to update values
    end
  end

  resources :artworks do
    resources :reviews
    resources :comments, module: :artworks do
    end
    member do
      put "like", to: "artworks#upvote"
      put "dislike", to: "artworks#downvote"
      patch 'create_picture'
      put 'set_completed' #put is used to update values
    end
  end 
  
   resources :comments do #is this needed??
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end
  resources :users, only: [:show, :index] do
    member do
      get :following, :followers
    end
  end


  resources :conversations do
    resources :messages
  end
  
  resources :relationships, only: [:create, :destroy]

  resources :reviews do
      put "approve", to: "reviews#approve"
    end
  

end

app/models/comment.rb
class Comment < ApplicationRecord
	acts_as_votable
	has_ancestry
  belongs_to :user
  belongs_to :commentable, polymorphic: true  #polymorphic association so that comments can be made on multiple models
  #test

  validates :comment, presence: true
end

app/controllers/artworks/comments_controller.rb
class Artworks::CommentsController < CommentsController
	before_action :set_commentable

	private

	def set_commentable
		@commentable = Artwork.find(params[:artwork_id])
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	#find if commentable is a post or an artowkr before building a new comment with that as the parent
	def new
		@parent_id = params.delete(:parent_id)
		@commentable = find_commentable
		@comment = Comment.new(:parent_id => @parent_id, :commentable_id => @commentable.id, :commentable_type => @commentable.class.to_s)
	end


	#redirect via ajax requirest when creating so no page refresh
	def create
		@commentable = find_commentable
		@comment = @commentable.comments.build(comment_params) # This is the line that causes the error
		@comment.user = current_user
		@comment.save

		respond_to do |format|
			format.html { redirect_to @commentable }
			format.js
		end

	end


	#destroy and redirect via ajax
	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		

		respond_to do |format|
			format.html { redirect_to @commentable }
			format.js
		end
	end


	# find comment via id and assign upvote from current user using ajax
	def upvote
		@comment = Comment.find(params[:id])
		@comment.upvote_by current_user
		
		respond_to do |format|
	    format.html { redirect_back(fallback_location: root_path) }
	    format.js
	  end
	end


	# find comment via id and assign downvote from current user using ajax
	def downvote
		@comment = Comment.find(params[:id])
		@comment.downvote_by current_user
		
		respond_to do |format|
	    format.html { redirect_back(fallback_location: root_path) }
	    format.js
	  end
	end

	private

	#assigned strong params
  def comment_params
    params.require(:comment).permit(:comment, :parent_id, :commentable_id, :commentable_type)
  end 


  #find parent type - either artwork or text post
  def find_commentable
  	params.each do |name, value|
  		if name =~ /(.+)_id$/
  			return $1.classify.constantize.find(value)
    	end
    end
    nil
  end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
	before_action :set_commentable

	private

	def set_commentable
		@commentable = Post.find(params[:post_id])
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
	
	def nested_comments(comments)
		comments.map do |comment, sub_comments|
			content_tag(:div, render(comment), class: 'commentContainer')
		end.join.html_safe
	end
end

app/views/comments/_comment.html.haml
.comment{:id => "comment_#{comment.id}"}
	.commentCurrent
		.commentMain
			.commentMainTop
				- if comment.user != nil
					.commentUserPic
						=image_tag comment.user.avatar.url(:thumb), :class => "commentUserThumb"
					%p
						=link_to comment.user.username, comment.user, :class => "commentUserName"
						commented:
				- else 
					%p [User Deleted]
			.commentMainContent
				%p= comment.comment
			.commentMainControls
				- if user_signed_in?
					
					= link_to "Reply", new_polymorphic_path([@commentable, Comment.new], :parent_id => comment, :id => @commentable), remote: true, :class => "replyLink btn btn-s btn-orange"
					- if comment.user != nil
						- if current_user.id == comment.user_id
							=link_to "Delete", [@commentable, comment] , method: :delete, remote: true, :data => { confirm: 'Delete Comment?',
																																										  'confirm-button-text': 'Delete',
																																										  'cancel-button-text': 'Cancel',
																																										  'confirm-button-color': '#ec8c25',
																																										  'cancel-button-color': '#151515',
																																										  'sweet-alert-type': 'warning'}, :class => "btn btn-s btn-dark btn-delete deleteLink"
		.commentVoting
			.voteSection.commentVoteSection
				.vote
					= link_to like_comment_path(comment), method: :put, remote: true do
						- if user_signed_in?
							- if current_user.voted_up_on? comment
								.triangle.arrow.voted
							-else
								.triangle.arrow
				.voteCount
					- @voteCount = (comment.get_upvotes.size) - (comment.get_downvotes.size)
					%p.commentVotes= @voteCount
				.vote
					= link_to dislike_comment_path(comment), method: :put, remote: true do
						- if user_signed_in?
							- if current_user.voted_down_on? comment
								.triangle.triDown.arrow.voted
							- else
								.triangle.triDown.arrow
	.commentReply
		= nested_comments comment.children

app/views/comments/_form.html.haml
.form
	.inner
		= form_for [@commentable, @comment], remote: true do |f|
			= f.hidden_field :parent_id
			.noticeBox
				- if @comment.errors.any?
					%h2 Errors:
					%ul
						- @comment.errors.full_messages.each do |message|
							%li= message
			.formItem.formInput.commentInput
				= f.text_area :comment
			.formItem.commentSubmitBtn
				= f.submit 'Submit Comment', disabled: true, :class => "commentSubmit btn btn-m btn-light btn-submit btn-disabled"

app/views/comments/create.js.erb
$('.commentReplyForm').remove(); //remove forms
$('.activeReply').show(); //show link again
$('.replyLink.activeReply').removeClass('activeReply'); //remove active reply class from all of them
$('.activeCommentReplySection').append('<%= j render "comment", :comment => @comment %>');
$('.activeCommentReplySection').removeClass('activeCommentReplySection'); //remove active reply section
$('.commentInput textarea').val('');
$('.noComments').hide();

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();

app/views/comments/downvote.js.erb
$('.activeVote').html('<%= j ((@comment.get_upvotes.size) - (@comment.get_downvotes.size)).to_s %>');

app/views/comments/edit.html.haml
%h1 Edit Reply
= simple_form_for([@post, @comment]) do |f|
	= f.input :comment
	= f.submit

app/views/comments/new.html.haml
%h2 Reply to Comment
= render 'form'

app/views/comments/new.js.erb
$('.activeReply').hide().after('<div class="commentReplyForm"><%= j render("form") %></div>');
$('.activeReply').parent().addClass("replyFormActive");
$('.commentReplyForm .commentSubmit').click(function() {
	// alert("comment reply button clicked");
	currentComment = $(this).closest('.comment');
	currentCommentReply = currentComment.children('.commentReply');
	$(currentCommentReply).addClass('activeCommentReplySection');
	//set the active reply zone to be under the current comment
	$('.commentMainControls').removeClass('replyFormActive'); //remove reply form styling
});


//button on reply form is only enabled when the text area contains a character
$('.commentReplyForm .commentInput textarea').keyup(function() {
	textLength = $('.commentReplyForm .commentInput textarea').val().length;
	if (textLength > 0) {
		//button is enabled
		$('.commentReplyForm .commentSubmitBtn input').attr('disabled',false); 
		$('.commentReplyForm .commentSubmitBtn input').removeClass('btn-disabled')
	} else {
		//button is disabled
		$('.commentReplyForm .commentSubmitBtn input').attr('disabled',true); 
		$('.commentReplyForm .commentSubmitBtn input').addClass('btn-disabled')
	}
});

app/views/comments/upvote.js.erb
$('.activeVote').html('<%= j ((@comment.get_upvotes.size) - (@comment.get_downvotes.size)).to_s %>');