config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  authenticated :user do
    root 'pages#home', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :authentications, only: [:destroy]

  root 'pages#home' #set site to default to the new home page

  resources :categories, shallow: true do 
    
    resources :posts
    get 'posts/tags/:tag', to: 'posts#index', as: 'post_tag'
    
    resources :artworks do
      resources :pictures do
        #should this be inside picture? - probably
        resources :notes, only: [:new, :create, :destroy]
      end
      member do
        patch 'create_picture'

      end
    end

    get 'artworks/tags/:tag', to: 'artworks#index', as: 'artwork_tag'
  end #end of categories
  
  
  resources :posts do

    resources :comments, module: :posts do
    end
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
      put 'set_completed' #put is used to update values
    end
  end

  resources :artworks do
    resources :reviews
    resources :comments, module: :artworks do
    end
    member do
      put "like", to: "artworks#upvote"
      put "dislike", to: "artworks#downvote"
      patch 'create_picture'
      put 'set_completed' #put is used to update values
    end
  end 
  
   resources :comments do #is this needed??
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end
  resources :users, only: [:show, :index] do
    member do
      get :following, :followers
    end
  end


  resources :conversations do
    resources :messages
  end
  
  resources :relationships, only: [:create, :destroy]

  resources :reviews do
      put "approve", to: "reviews#approve"
    end
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  validates :email, presence: :true, uniqueness: { case_sensitive: false }

  has_many :posts
  has_many :artworks
  has_many :comments
  has_many :reviews
  has_many :notes

  acts_as_voter

  has_attached_file :avatar, styles: { medium: "200x200#", thumb: "50x50#" }, default_url: "blankAvatar.png"

  #ActionController::Base.helpers.asset_path
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :conversations, :foreign_key => :sender_id, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy #destroying a user also destroys their relationships

  has_many :passive_relationships, class_name: "Relationship",
                                    foreign_key: "followed_id",
                                    dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower


  def postFeed
    following_ids = "SELECT followed_id FROM relationships WHERE  follower_id = :user_id"
    Post.where("user_id IN (#{following_ids})", user_id: id) 
    #returns a feed of posts with following user's ids, with a second sql snippet injected
  end

  def artworkFeed
    following_ids = "SELECT followed_id FROM relationships WHERE  follower_id = :user_id"
    Artwork.all.where("user_id IN (#{following_ids})", user_id: id) 
    #returns a feed of artworks with following user's ids, with a second sql snippet injected
  end

  #follows a user
  def follow(other_user)
    following << other_user
  end

  #unfollows a user
  def unfollow(other_user)
    following.delete(other_user)
  end

  #returns true if the current user is following another user
  def following?(other_user)
    following.include?(other_user)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name
      user.save
    end
  end

  def apply_omniauth(auth)
    update_attributes(
        provider: auth.provider,
        uid: auth.uid
      )
  end

  def has_facebook_linked?
    self.provider.present? && self.uid.present?
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

	#account linking from edit profile page
	# if current user exists then apply omniauth and link account
	def facebook
	  if current_user.present?
	    current_user.apply_omniauth(request.env["omniauth.auth"])
	    redirect_to edit_user_registration_path, notice: "Facebook Account Linked!"
	  else
	    @user = User.from_omniauth(request.env["omniauth.auth"])
		  if @user
		    sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
		    set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
		  else
		    session["devise.facebook_data"] = request.env["omniauth.auth"]
		    #if failed redirect to sign up page
		    redirect_to new_user_registration_url
		  end
	  end
	end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

	# Overwrite update_resource to let users to update their user without giving their password
  def update_resource(resource, params)
    if resource.provider == "facebook"
      params.delete("current_password")
      resource.update_without_password(params)
      #update without password is provider is fb
    else
      resource.update_with_password(params)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#users_controller.rb
before_action :authenticate_user!, except: [:show] 
#make sure user is signed in to access any pages, except for the show page so that others can view it


def index
	@search = User.ransack(params[:q])
	@users = @search.result.paginate(page: params[:page], per_page: 10)
	#fetch all users as filtered by the search bar
end

#find current user with id, the fetch all artworks and posts by that user
def show
  @user = User.find(params[:id])
  @artworks = @user.artworks.paginate(page: params[:page], per_page: 10)
  @posts = @user.posts.paginate(page: params[:page], per_page: 10)
  @comments = @user.comments
  @page = "userHome"
end

#select all of the current user's following list for display purposes - this page isnt used
def following
	@title = "Following"
	@user = User.find(params[:id])
	@users = @user.following
	render 'show_follow'
end

#select all of the current user's followers list for display purposes - this page isnt used
def followers
	@title = "Followers"
	@user = User.find(params[:id])
	@users = @user.followers
	render 'show_follow'
end


private
#defined strong params 
def user_params
	params.require(:user).permit(:username, :email, :password, :avatar)
end

end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.haml
= form_for(current_user.active_relationships.build) do |f|
	= hidden_field_tag :followed_id, @user.id
	= f.submit "Follow", :class => "btn btn-m btn-orange"

app/views/users/_follow_form.html.haml
- unless current_user == @user
	.followForm
		- if current_user.following?(@user)
			= render 'unfollow'
		- else
			= render 'follow'

app/views/users/_unfollow.html.haml
= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete}) do |f|
	= f.submit "Unfollow", :class => "btn btn-m btn-orange"

app/views/users/index.html.haml
%h3.convoTitle All Users

.userSearch
	.searchForm.userSearch
		= search_form_for @search, :class => "searchBar" do |f|
			.searchInput
				= f.search_field :username_cont
			= f.submit 'Search', :class => "btn btn-m btn-light"
.userList
	- if @users.size == 0
		%p.noPosts No Results...
	-else
		- @users.each do |user|
			.userTile
				.convoUserThumb
					=image_tag user.avatar.url(:thumb), :class => "artUserThumb"
					- if user.id == current_user.id
						=link_to "Me", user, :class => "artUserName"
					-else 
						=link_to user.username, user, :class => "artUserName"
				.userMsgButton
					= link_to 'Message', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post', :class => "btn btn-m btn-orange"
	= will_paginate @users, inner_window: 1, outer_window: 0

app/views/users/show.html.haml
.titleSection.sixtySection
	%h1.threadTitle
		= @user.username + "'s"
		Profile


.profileSection.sixtySection
	.profileInner
		.profilePicSection
			= image_tag @user.avatar.url(:medium)
		.profileInfoSection
			.profileInfo
				%p
					Member Since:
					= @user.created_at.strftime("%d/%m/%Y")
				%p
					Posts: 
					= (@user.artworks.size) + (@user.posts.size)
				%p
					Comments: 
					= @user.comments.size
				%p
					Reviews: 
					= @user.reviews.size
				%p
					Notes: 
					= @user.notes.size
				%p.following
					Following:
					= @user.following.count
				%p.followers
					Followers
					= @user.followers.count

			.profileControls
				- if user_signed_in?
					- if current_user == @user #if current user's page then add sign put button
						= link_to "Edit Profile", edit_user_registration_path, :class => "btn btn-m btn-dark"
						= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => "btn btn-m btn-orange"
					- else
						= link_to 'Message', conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: 'post', :class => "btn btn-m btn-dark"
						= render 'follow_form'

.userArtToggle.galSection
	%h3.commentHeader Artwork Posts: 
	=image_tag "toggleUpDark.png", :class => "darkToggleArrow" 
.userArtContent
	- if @user.artworks.size == 0
		.noContent
			%p This user hasnt posted any artworks yet!
	- else
		.artworkThumbSection
			#arts.transitions-enabled
				- @artworks.each do |artwork|
					.artSpacer
						%div.artworkContainer
							.thumbnail
								- if artwork.pictures.any?
									.thumbToggles
										- i = 1 # counter to assign class names to toggles
										- unless artwork.pictures.size <= 1
											- while (i <= artwork.pictures.size) do
												.tToggle{:id => i.to_s} 
												- i+=1 #add one to counter per loop

									- c = 1 #counter to assign class names to thumbs
									- artwork.pictures.each do |p|
										.thumbImg{class: "hidden thumb-" + c.to_s}
											= image_tag p.image.url
										- c+=1 #add one to counter per loop
							.infoSection	
								.info
									%h2.title= link_to artwork.title, artwork
									%p.category
										- if artwork.category_id == nil
											Uncategorized
										- else
											= Category.find(artwork.category_id).name
									%p
										Tags: 
										= raw artwork.tag_list.map { |t| link_to t, category_artwork_tag_path(artwork.category_id, t), :class => "tagLink"}.join(', ')
									%p
										- if artwork.completed == true
											%p.answered Completed
										- else
											%p.unanswered In Progress
									%p
										- if artwork.nsfw == true
											%p.nsfw NSFW

								.voteSection.artVoteSection	
									.vote
										= link_to like_artwork_path(artwork), method: :put, remote: true do
											- if user_signed_in?
												- if current_user.voted_up_on? artwork
													.triangle.arrow.voted
												-else
													.triangle.arrow
									.voteCount
										%p.artVotes= @voteCount = (artwork.get_upvotes.size) - (artwork.get_downvotes.size)
									.vote
										= link_to dislike_artwork_path(artwork), method: :put, remote: true do
											- if user_signed_in?
												- if current_user.voted_down_on? artwork
													.triangle.triDown.arrow.voted
												- else
													.triangle.triDown.arrow
							.extraInfo	
								.userThumb
									=image_tag artwork.user.avatar.url(:thumb), :class => "artUserThumb"
									=link_to artwork.user.username, artwork.user, :class => "artUserName"
								%p.date
									Posted 
									= time_ago_in_words(artwork.created_at)
									ago
	= will_paginate @artworks, inner_window: 1, outer_window: 0


.userPostToggle.galSection
	%h3.commentHeader Question Posts: 
	=image_tag "toggleUpDark.png", :class => "darkToggleArrow" 
.userPostContent
	- if @user.posts.size == 0
		.noContent
			%p This user hasnt posted any questions yet!
	- else
		.gallery
		- @posts.each do |post|
			.postContainer
				.postThumbLeft
					.leftInner
						.leftUpper.leftSection
							%h2.title= link_to post.title, post
						.leftLower.leftSection
							%p
								- if post.category_id == nil
									Uncategorized
								- else 
									= Category.find(post.category_id).name
							%p
								Tags: 
								= raw post.tag_list.map { |t| link_to t, category_post_tag_path(post.category_id, t), :class => "tagLink"}.join(', ')
							%p
								- if post.completed == true
									%p.answered Answered
								- else
									%p.unanswered Unanswered
					.voteSection.postVoteSection	
						.vote
							= link_to like_post_path(post), method: :put, remote: true do
								- if user_signed_in?
									- if current_user.voted_up_on? post
										.triangle.arrow.voted
									-else
										.triangle.arrow
						.voteCount
							%p.postVotes= @voteCount = (post.get_upvotes.size) - (post.get_downvotes.size)
						.vote
							= link_to dislike_post_path(post), method: :put, remote: true do
								- if user_signed_in?
									- if current_user.voted_down_on? post
										.triangle.triDown.arrow.voted
									- else
										.triangle.triDown.arrow
				.postThumbRight
					- if post.user != nil
						.userThumb
							=image_tag post.user.avatar.url(:thumb), :class => "artUserThumb"
							=link_to post.user.username, post.user, :class => "artUserName"
					-else
						%p [User Deleted]		
					%p.date
						Posted
						= time_ago_in_words(post.created_at)
						ago
	= will_paginate @posts, inner_window: 1, outer_window: 0


%script{type: "text/javascript"}
	:plain
		$('.thumb-1').addClass('visible');
		$('.thumb-1').removeClass('hidden');

		$('.thumbnail').hover(function() {
			var activeThumb = this;
			$('.tToggle', activeThumb).hover(function() {
				var num = this.id;
				var thumbClass = "thumb-"+num;
				$('.thumbImg', activeThumb).removeClass('visible');
				$('.thumbImg', activeThumb).addClass('hidden');
				$('.'+thumbClass, activeThumb).addClass('visible');
				$('.'+thumbClass, activeThumb).removeClass('hidden');
			});
		});


					

app/views/users/show_follow.html.haml
%h2= @title

- @users.each do |user|
	.user
		%p= user.username
		= link_to "View Profile", user