config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  authenticated :user do
    root 'pages#home', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :authentications, only: [:destroy]

  root 'pages#home' #set site to default to the new home page

  resources :categories, shallow: true do 
    
    resources :posts
    get 'posts/tags/:tag', to: 'posts#index', as: 'post_tag'
    
    resources :artworks do
      resources :pictures do
        #should this be inside picture? - probably
        resources :notes, only: [:new, :create, :destroy]
      end
      member do
        patch 'create_picture'

      end
    end

    get 'artworks/tags/:tag', to: 'artworks#index', as: 'artwork_tag'
  end #end of categories
  
  
  resources :posts do

    resources :comments, module: :posts do
    end
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
      put 'set_completed' #put is used to update values
    end
  end

  resources :artworks do
    resources :reviews
    resources :comments, module: :artworks do
    end
    member do
      put "like", to: "artworks#upvote"
      put "dislike", to: "artworks#downvote"
      patch 'create_picture'
      put 'set_completed' #put is used to update values
    end
  end 
  
   resources :comments do #is this needed??
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end
  resources :users, only: [:show, :index] do
    member do
      get :following, :followers
    end
  end


  resources :conversations do
    resources :messages
  end
  
  resources :relationships, only: [:create, :destroy]

  resources :reviews do
      put "approve", to: "reviews#approve"
    end
  

end

app/models/post.rb
class Post < ApplicationRecord
	acts_as_votable
	acts_as_taggable
	belongs_to :user
	belongs_to :category
	has_many :comments, as: :commentable, :dependent => :destroy #polymorphic association so that comments can be made on multiple models

	validates :title, :content, presence: true

end 

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
	before_action :set_commentable

	private

	def set_commentable
		@commentable = Post.find(params[:post_id])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy] #so that code doesnt have to be repeated
	before_action :find_category, only: [:index]
	before_action :authenticate_user!, except: [:index, :show] #makes sure the user cannot just path to a new post page without signing in
	include Commentable

	def index #index through all of the various posts
		@page = "index"
		@categories = Category.all

		#if all category is displayed fetch all posts from all cats
		if @category.id == 1 
			#if a tag has been selected assign a title and sort via tag too
			if params[:tag]
				@tagPresent = true
				@tagName = params[:tag]
				@allPosts = Post.all
				@search = @allPosts.tagged_with(params[:tag]).ransack(params[:q])
		  		@posts = @search.result.paginate(page: params[:page], per_page: 5)
			else
				@tagPresent = false
				@allPosts = Post.all
				@search = @allPosts.ransack(params[:q])
		  		@posts = @search.result.paginate(page: params[:page], per_page: 5)
			end
			#else find posts from specific category
		else
			#sort via tag and define title
			if params[:tag]
				@tagPresent = true
				@tagName = params[:tag]
				@search = @category.posts.tagged_with(params[:tag]).ransack(params[:q])
	  			@posts = @search.result.paginate(page: params[:page], per_page: 5)
			else
				@tagPresent = false
				@search = @category.posts.ransack(params[:q])
	  			@posts = @search.result.paginate(page: params[:page], per_page: 5)
			end
		end
	end

	def show
		@page = 'postShow'
	end

	#define category list for form excluding all category
	def new
		@categories = Category.all.reject { |c| c.name == "All" }.map{|c| [c.name, c.id] }
		@post = current_user.posts.build
	end


	# build post, set completed to false and redirect to the new post if successful
	def create
		@categories = Category.all.reject { |c| c.name == "All" }.map{|c| [c.name, c.id] }
		@post = current_user.posts.build(post_params)
		@post.completed = false;
		if @post.save
			redirect_to @post, notice: "Post submitted successfully"
		else
			render 'new' #else render the form again
		end
	end

	#editing post is not possible
	def edit
		@categories = Category.all.map{|c| [c.name, c.id] }
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	#remove post and return to all posts page
	def destroy
		@post.destroy
		redirect_to category_posts_path(1) #posts forum index page cat 1
	end

	#find post with id and assign an upvote by the current user using ajax
	def upvote
		@post = Post.find(params[:id])
		@post.upvote_by current_user
		
		respond_to do |format|
	    format.html { redirect_back(fallback_location: root_path) }
	    format.js
	  end
	end

	#find post with id and assign an downvote by the current user using ajax
	def downvote
		@post = Post.find(params[:id])
		@post.downvote_by current_user
		
		respond_to do |format|
	    format.html { redirect_back(fallback_location: root_path) }
	    format.js
	  end
	end

	#find post using id anmd set db attribute to true, then redirect to the post to refresh page
	def set_completed
		@post = Post.find(params[:id])
		@post.update_attribute(:completed, true)
		redirect_to @post
	end

	private

	def find_post
		@post = Post.find(params[:id])
	end

	def find_category
		@category = Category.find(params[:category_id])
	end

	#defined strong params for the post
	def post_params
		params.require(:post).permit(:title, :content, :tag_list, :category_id, :nsfw)
	end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
.form.sixtySection
	.inner
		= simple_form_for @post, :url => category_posts_path do |f|
			.formHeader
				%h2 New Question
				=link_to "Cancel", root_path, :class => "btn btn-m btn-dark"
			.noticeBox
				- if @post.errors.any?
					%h2 Errors:
					%ul
						- @post.errors.full_messages.each do |message|
							%li= message
			.formItem.formInput
				.labelContainer
					= f.label :title, "Post Title"
					%p.prompt.required *
				= f.input :title, label: false
			.formItem.formInput
				.labelContainer
					= f.label :content, "Post Content"
					%p.prompt.required *
				= f.input :content, label: false
			.formItem.formInput
				.labelContainer
					= f.label :tag_list, "Tags"
					%p.prompt Separated with commas
				= f.input :tag_list, label: false
			.formItem
				= f.label :category_id, "Art or Design Category"
				= f.select(:category_id, options_for_select(@categories))
			.formItem.labelItem
				%p.formLabel Does your post contain adult content?
				= f.label :nsfw,:class => "checkContainer checkContainerForm" do
					= f.check_box :nsfw
					%span.checkmark
			.formItem
				= f.submit 'Submit Post', :class => "btn btn-m btn-light btn-submit"
			
	

app/views/posts/_postGallery.html.haml
.gallery
	.galleryTopbar
		%h1.forumTitle Questions Forum
		%p= @category.name
			
		- if user_signed_in?
			= link_to "Submit Question", new_post_path

		/ = search_form_for @search, :class => "searchBar" do |f|
		/ 	= f.search_field :title_cont 
		/ 	= f.submit		

	- @posts.each do |post|
		- if post.category_id.to_i == @category.id
			.postContainer
				.postThumbLeft
					.leftUpper.leftSection
						%h2.title= link_to post.title, post
						%p.date
							Published
							= time_ago_in_words(post.created_at)
							ago
					.leftLower.leftSection
						%p 
							Upvotes:
							= post.get_upvotes.size
						%p
							Comment (
							= post.comments.size
							)
						%p
							- if post.answered == true
								%p.answered Answered
							- else
								%p.unanswered Unanswered
						%p
							Category:
							- if post.category_id == nil
								Uncategorized
							- else 
								= Category.find(post.category_id).name
				.postThumbRight
					.profileIcon
						=image_tag post.user.avatar.url(:thumb)
				

app/views/posts/downvote.js.erb
$('.activeVote').html('<%= j ((@post.get_upvotes.size) - (@post.get_downvotes.size)).to_s %>');

app/views/posts/edit.html.haml
= render 'form'

= link_to "Cancel", post_path

app/views/posts/index.html.haml
.mainBody
	= render partial: 'layouts/sidebar', locals: { section: 2 } # 2 for posts
	.gallery
		.galleryTopbar
			.titleSubmit
				.titleAndSub
					%h1.forumTitle
						=@category.name
						Posts
					- if @tagPresent 
						%p.tagTitle
							Filtered by Tag: 
							= @tagName
				.submitButton
					- if user_signed_in?
						= link_to "Submit", new_category_post_path, :class => "btn btn-m btn-orange"
			.searchForm
				= search_form_for [@category, @search], :class => "searchBar" do |f|
					.searchInput
						= f.search_field :title_cont
					= f.submit 'Search', :class => "btn btn-m btn-light"
		- if @posts.size == 0
			%p.noPosts No posts found...Try searching again!
		- else
			- @posts.each do |post|
				.postContainer
					.postThumbLeft
						.leftInner
							.leftUpper.leftSection
								%h2.title= link_to post.title, post
							.leftLower.leftSection
								%p
									- if post.category_id == nil
										Uncategorized
									- else 
										= Category.find(post.category_id).name
								%p
									Tags: 
									= raw post.tag_list.map { |t| link_to t, category_post_tag_path(post.category_id, t), :class => "tagLink"}.join(', ')
								- if post.nsfw == true
									%p.nsfw NSFW
								- if post.completed == true
									%p.answered Answered
								- else
									%p.unanswered Unanswered
								

						.voteSection.postVoteSection	
							.vote
								= link_to like_post_path(post), method: :put, remote: true do
									- if user_signed_in?
										- if current_user.voted_up_on? post
											.triangle.arrow.voted
										-else
											.triangle.arrow
							.voteCount
								%p.postVotes= @voteCount = (post.get_upvotes.size) - (post.get_downvotes.size)
							.vote
								= link_to dislike_post_path(post), method: :put, remote: true do
									- if user_signed_in?
										- if current_user.voted_down_on? post
											.triangle.triDown.arrow.voted
										- else
											.triangle.triDown.arrow
					.postThumbRight
						- if post.user != nil
							.userThumb
								=image_tag post.user.avatar.url(:thumb), :class => "artUserThumb"
								=link_to post.user.username, post.user, :class => "artUserName"
						-else
							%p [User Deleted]		
						%p.date
							Posted
							= time_ago_in_words(post.created_at)
							ago
		= will_paginate @posts, inner_window: 1, outer_window: 0

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
.backSection.sixtySection
	- @cat = Category.find(@post.category_id).name
	= link_to "Back to " + @cat, category_posts_path(@post.category_id), :class => "btn btn-s btn-dark"
.titleSection.sixtySection
	%h1.threadTitle= @post.title
.questionSection.sixtySection
	%p= @post.content

.descriptionSection.sixtySection
	.descInfo.descSection
		%p
			- if @post.category_id == nil
				Uncategorized
			- else 
				=link_to @cat, category_posts_path(@post.category_id), :class => "catLink"
		%p
			Tags: 
			= raw @post.tag_list.map { |t| link_to t, category_post_tag_path(@post.category_id, t), :class => "tagLink"}.join(', ')
		- if @post.completed == true
			%p.answered Answered
		- else
			%p.unanswered Unanswered
		- if @post.nsfw == true
			%p.nsfw NSFW
	.descTop
		.descUser.descSection
			- if @post.user != nil
				.userThumb
					=image_tag @post.user.avatar.url(:thumb), :class => "artUserThumb"
					=link_to @post.user.username, @post.user, :class => "artUserName"
			- else
				%p [User Deleted]
		.descVoting.descSection
			.voteSection.postVoteSection	
				.vote
					= link_to like_post_path(@post), method: :put, remote: true do
						- if user_signed_in?
							- if current_user.voted_up_on? @post
								.triangle.arrow.voted
							-else
								.triangle.arrow
				.voteCount
					%p.postVotes= @voteCount = (@post.get_upvotes.size) - (@post.get_downvotes.size)
				.vote
					= link_to dislike_post_path(@post), method: :put, remote: true do
						- if user_signed_in?
							- if current_user.voted_down_on? @post
								.triangle.triDown.arrow.voted
							- else
								.triangle.triDown.arrow
	.descDate.descSection
		%p.date
			Posted
			= time_ago_in_words(@post.created_at)
			ago
		.descSocial
			.sIcon.facebookIcon
				= facebook_button :turbolinks => true, :app_id => '2095083210778655', :static_link => true, :share => true
			.sIcon.twitterIcon
				= twitter_button :turbolinks => true, :title=> 'Crittr - ' + @post.title,  :hashtags => "Crittr", :static_link => true
			.sIcon.redditIcon	
				= reddit_button :turbolinks => true, :title=> 'Crittr - ' + @post.title , :static_link => true

	.descControls.descSection
		- if user_signed_in?
			- if @post.user != nil
				- if current_user.id == @post.user_id
					= link_to "Delete Question", post_path(@post), method: :delete, :data => { confirm: 'Delete Question Post?',
																																										  'confirm-button-text': 'Delete',
																																										  'cancel-button-text': 'Cancel',
																																										  'confirm-button-color': '#ec8c25',
																																										  'cancel-button-color': '#151515',
																																										  'sweet-alert-type': 'warning'}, :class => "btn btn-m btn-dark"
					- if @post.completed != true
						= link_to "Set as Answered", set_completed_post_path(@post), method: :put, :data => { confirm: 'Set as Answered?',
																																										  'confirm-button-text': 'Yes',
																																										  'cancel-button-text': 'No',
																																										  'confirm-button-color': '#ec8c25',
																																										  'cancel-button-color': '#151515',
																																										  text: 'If your question has been answered, select yes',
																																										  'sweet-alert-type': 'info'}, :class => "btn btn-m btn-orange"



.commentToggle.sixtySection
	%h3.commentHeader Comments
	=image_tag "toggleUpDark.png", :class => "darkToggleArrow" 
.commentShrinkSection
	.commentContent.sixtySection
		- if @comments.size == 0
			%p.noComments No Comments yet!
		-else	
			= nested_comments @comments
	.commentFormSection.sixtySection
		- if user_signed_in?
			.showForm
				= render partial: "comments/form", locals: {commentable: @post}
		- else
			%p Sign in to comment		

app/views/posts/upvote.js.erb
// alert("Liked");
$('.activeVote').html('<%= j ((@post.get_upvotes.size) - (@post.get_downvotes.size)).to_s %>');