config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  authenticated :user do
    root 'pages#home', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :authentications, only: [:destroy]

  root 'pages#home' #set site to default to the new home page

  resources :categories, shallow: true do 
    
    resources :posts
    get 'posts/tags/:tag', to: 'posts#index', as: 'post_tag'
    
    resources :artworks do
      resources :pictures do
        #should this be inside picture? - probably
        resources :notes, only: [:new, :create, :destroy]
      end
      member do
        patch 'create_picture'

      end
    end

    get 'artworks/tags/:tag', to: 'artworks#index', as: 'artwork_tag'
  end #end of categories
  
  
  resources :posts do

    resources :comments, module: :posts do
    end
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
      put 'set_completed' #put is used to update values
    end
  end

  resources :artworks do
    resources :reviews
    resources :comments, module: :artworks do
    end
    member do
      put "like", to: "artworks#upvote"
      put "dislike", to: "artworks#downvote"
      patch 'create_picture'
      put 'set_completed' #put is used to update values
    end
  end 
  
   resources :comments do #is this needed??
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end
  resources :users, only: [:show, :index] do
    member do
      get :following, :followers
    end
  end


  resources :conversations do
    resources :messages
  end
  
  resources :relationships, only: [:create, :destroy]

  resources :reviews do
      put "approve", to: "reviews#approve"
    end
  

end

app/views/layouts/_notice.html.haml
.container    
	%p.notice
		= notice
	%p.alert
		= alert

app/views/layouts/_sidebar.html.haml
.sidebar
	.sidebarContent
		.content
			%h2.sideHeader Forum
			.contentBox
				.fLinkFlex
					= link_to "Artwork", category_artworks_path(1), :class => "btn btn-m btn-light sidebarForumLink"
				.fLinkFlex
					= link_to "Question", category_posts_path(1), :class => "btn btn-m btn-light sidebarForumLink"
			.contentBox
				%h2.sideHeader Category
				.contentFlexSect
					- if section == 1 #if artwork forum links go to artwork forum path
						- @categories.each do |cat|
							= link_to cat.name, category_artworks_path(cat.id), :class => "contentLink"
					- else # else it links to the posts forum
						- @categories.each do |cat|
							= link_to cat.name, category_posts_path(cat.id), :class => "contentLink"
			.contentBox
				%h2.sideHeader Sort By
				.contentFlexSect
					=sort_link(@search, :created_at, "Date Created")
					=sort_link(@search, :title, "By Title")
					=sort_link(@search, :cached_votes_up, "By Upvotes")
					=sort_link(@search, :cached_votes_down, "By Downvotes")
			.contentBox
				%h2.sideHeader Filter
				= search_form_for [@category, @search], :class => "filterBar" do |f|
					.contentFilterItem
						= f.label :nsfw_false, :class => "checkContainer" do
							Hide NSFW
							= f.check_box :nsfw_false
							%span.checkmark
					.contentFilterSubmit		
						= f.submit 'Filter', :class => "btn btn-m btn-light"
			.contentPaddingSection
	.sidebarToggle
		=image_tag "toggleDown.png", :class => "toggleArrow toggleSide"  

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Crittr
  = csrf_meta_tags 
  = tag 'meta', {:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0", :name => "viewport"}, true
  = stylesheet_link_tag 'application', media: 'all'
  %link{ "rel" => "stylesheet", href: "https://fonts.googleapis.com/css?family=Heebo:400,700", type: "text/css"}
  = javascript_include_tag 'application'
  = favicon_link_tag 'favicon.png', rel: 'shortcut icon', type: 'image/png'
  
  


  
%body
  %header.topBar
    = link_to root_path, class: "logo" do 
      =image_tag "crittrLogo.png", :class => "topLogo"      
    .profileButtons
      - if user_signed_in?
        .profileMenuSection
          .dropDown
            .dropControls
              %button.dropBtn &#x25BC
              .profileThumb
                = image_tag current_user.avatar.url(:thumb) 
            .dropDownContent
              = link_to "User Profile", current_user
              = link_to "Messages", conversations_path
              = link_to "Sign Out", destroy_user_session_path, method: :delete  
          
      -else
        = link_to "Sign Up", new_user_registration_path, :class => "topBarLink"
        = link_to "Sign In", new_user_session_path, :class => "topBarLink"



  .postsContainer
    =yield
    
  - if @page == 'newNote'
    = javascript_include_tag '/javascripts/createNote.js', type: "text/javascript"

  - if @page == 'artShow'
    = javascript_include_tag '/javascripts/artShow.js', type: "text/javascript"

  - if @page == 'postShow'
    = javascript_include_tag '/javascripts/postShow.js', type: "text/javascript"

  - if @page == 'index'
    = javascript_include_tag '/javascripts/indexPage.js', type: "text/javascript"

  - if @page == 'userHome'
    = javascript_include_tag '/javascripts/userHome.js', type: "text/javascript"

  - if @page == 'artNew'
    = javascript_include_tag '/javascripts/artNew.js', type: "text/javascript"
 
  